import type { Metadata } from "next";
import { Montserrat, Oswald } from "next/font/google";
import "./globals.scss";

import Footer from "./components/layout/Footer/Footer";


// Montserrat шрифт
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"], // Добавляем поддержку кириллицы
  weight: ["300", "400", "500", "600", "700"], // Указываем нужные начертания
  style: ["normal", "italic"], // Обычный и курсив
});

// Oswald шрифт
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin", "cyrillic"], // Добавляем поддержку кириллицы
  weight: ["300", "400", "500", "600", "700"], // Указываем нужные начертания
});

export const metadata: Metadata = {
  title: "К Х М",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${montserrat.variable} ${oswald.variable}`}>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
